# Generated by Django 5.0.1 on 2024-01-03 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_details', models.TextField(max_length=255)),
                ('tag', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('N', 'New'), ('H', 'Hot'), ('W', 'Won'), ('L', 'Lost')], default='N', max_length=1)),
                ('follow_up_date', models.DateField()),
                ('phone', models.IntegerField(verbose_name=django.core.validators.MaxLengthValidator('Phone number should be in 10 digits', 10))),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
