# Generated by Django 5.0.1 on 2024-01-03 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.MaxLengthValidator(limit_value=10, message='Phone number must be 10 digits or less')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.IntegerField(null=True, verbose_name=django.core.validators.MaxLengthValidator('Phone number should be in 10 digits', 10)),
        ),
    ]
