# Generated by Django 5.0.1 on 2024-01-03 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_flow', '0002_lead_phone_number_alter_lead_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='phone',
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(limit_value=10, message='Phone number must be 10 digits')]),
        ),
    ]
