# Generated by Django 5.0.1 on 2024-01-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_flow', '0004_alter_lead_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
