# Generated by Django 5.0.1 on 2024-01-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_flow', '0005_lead_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('H', 'Hot'), ('W', 'Won'), ('L', 'Lost')], default='N', max_length=50),
        ),
    ]
