# Generated by Django 5.0.1 on 2024-04-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_flow', '0009_alter_lead_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='person',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
